environments:
  dev:
    environment_variables:
      EXAMPLE_DEPLOYMENT: testing
    pipelines:
      - docker-cfndsl
pipelines:
  docker-cfndsl:
    group: platform-team
    materials:
      mygit:  # this is the name of material
        # says about type of material and url at once
        git: https://github.com/pkumaschow/cfndsl.git
    stages:
      - build: # name of stage
          jobs:
            build: # name of the job
              tasks:
               - exec: # indicates type of task
                   command: docker build -t cfndsl .
